In [ ]:
pip install json-lines

In [ ]:
import jsonlines

In [10]:
j_array =[]
with open('clickbait17-train-170630/clickbait17-validation-170630/instances.jsonl', 'rb') as f:
    for item in json_lines.reader(f):
       j_array.append(item)

In [17]:
import pandas as pd
df = pd.DataFrame(j_array)

In [18]:
df.head(100)

,postMedia,postText,id,targetCaptions,targetParagraphs,targetTitle,postTimestamp,targetKeywords,targetDescription
0,[],[UK’s response to modern slavery leaving victi...,858462320779026433,[modern-slavery-rex.jpg],[Thousands of modern slavery victims have not ...,‘Inexcusable’ failures in UK’s response to mod...,Sat Apr 29 23:25:41 +0000 2017,"modern slavery, Department For Work And Pensio...",“Inexcusable” failures in the UK’s system for ...
1,[],[this is good],858421020331560960,"[In this July 1, 2010 file photo, Dr. Charmain...",[President Donald Trump has appointed the pro-...,Donald Trump Appoints Pro-Life Advocate as Ass...,Sat Apr 29 20:41:34 +0000 2017,"Americans United for Life, Dr. Charmaine Yoest...",President Donald Trump has appointed pro-life ...
2,[],"[The ""forgotten"" Trump roast: Relive his bruta...",858368123753435136,[President Trump will not attend this year's W...,[When the White House correspondents’ dinner i...,The ‘forgotten’ Trump roast: Relive his brutal...,Sat Apr 29 17:11:23 +0000 2017,"trump whcd, whcd, white house correspondents d...",President Trump won't be at this year's White ...
3,[],[Meet the happiest #dog in the world!],858323428260139008,"[Maru , Maru, Maru, Maru, Maru]",[Adorable is probably an understatement. This ...,"Meet The Happiest Dog In The World, Maru The H...",Sat Apr 29 14:13:46 +0000 2017,"Maru, husky, dogs, pandas, furball, instagram","The article is about Maru, a husky dog who has..."
4,[],[Tokyo's subway is shut down amid fears over a...,858283602626347008,[All nine lines of Tokyo's subway system were ...,[One of Tokyo's major subways systems says it ...,Tokyo's subway is shut down amid fears over an...,Sat Apr 29 11:35:31 +0000 2017,"Tokyo,subway,shut,fears,North,Korean,attack","The temporary suspension, which lasted ten min..."

In [19]:
t_array =[]
with open('clickbait17-train-170630/clickbait17-validation-170630/truth.jsonl', 'rb') as f:
    for item in json_lines.reader(f):
       t_array.append(item)

In [30]:
df_truth = pd.DataFrame(t_array)
df_truth[df_truth['id']=='858323428260139008']

,truthJudgments,truthMean,id,truthClass,truthMedian,truthMode
64,"[1.0, 0.6666666666, 1.0, 1.0, 1.0]",0.933333,858323428260139008,clickbait,1.0,1.0